FROM python:3.12.7-bullseye

RUN apt update \
&& apt install git

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY . /app

WORKDIR /app

ENTRYPOINT [ "/bin/bash" ]

EXPOSE 5801

CMD ["run.sh"]